name: Playbook

description: CIのJOBが落ちた時にどのように対応するべきかを書く

inputs:
  message:
    description: "How to fix?"
    required: true

runs:
  using: composite
  steps:
    - name: How to Fix?
      uses: actions/github-script@v7
      env:
        INPUT_MESSAGE: ${{ inputs.message }}
      with:
        script: |
          const message = process.env.INPUT_MESSAGE
          console.log(`Hello ${message}`)
