name: Playbook

description: CIのJOBが落ちたときにどのように対応するべきかをSummaryに出力します

inputs:
  message:
    description: How to fix?
    required: true

runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      env:
        INPUT_MESSAGE: ${{ inputs.message }}
      with:
        script: |
          const message = process.env.INPUT_MESSAGE
          core.summary.addRaw(message, true)
          core.summary.write()
