# Directory Patterns
':elephant: server':
  - changed-files:
    - any-glob-to-any-file:
      - app/**
      - config/**
      - database/**
      - lang/**
      - routes/**
      - tests/**
      - composer.json
':fish: front':
  - changed-files:
    - any-glob-to-any-file:
      - resources/**
      - package.json

# Branch Patterns
':gem: feat':
  - head-branch:
    - '^feature/'
    - '^feat/'
':bug: fix':
  - head-branch:
    - '^fix/'
':rocket: release':
  - head-branch:
    - '^release/'
