# Directory Patterns
':elephant: server':
  - changed-files:
    - any-glob-to-any-file:
      - app/**
      - config/**
      - database/**
      - lang/**
      - routes/**
      - tests/**
      - composer.json
':fish: front':
  - changed-files:
    - any-glob-to-any-file:
      - resources/**
      - package.json
':electric_plug: infrastructure':
  - changed-files:
    - any-glob-to-any-file:
      - terraform/**
':octocat: github':
  - changed-files:
    - any-glob-to-any-file:
      - .github/**
':whale2: docker':
  - changed-files:
      - any-glob-to-any-file:
          - docker/**
          - docker-compose.yaml
':package: package':
  - changed-files:
    - any-glob-to-any-file:
      - composer.json
      - composer.lock
      - package.json
      - package-lock.json
      - yarn.lock
':card_file_box: migration':
  - changed-files:
    - any-glob-to-any-file:
      - database/migrations/*.php

# Branch Patterns
':gem: feat':
  - head-branch:
    - '^feature/'
    - '^feat/'
':bug: fix':
  - head-branch:
    - '^fix/'
':rocket: release':
  - head-branch:
    - '^release/'
