name: Auto Commit

on:
#  schedule:
#    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: ☕ Auto Commit
          commit_options: '--allow-empty'
          skip_dirty_check: true
