name: Auto Action Lint

on:
  push:
    paths:
      - '.github/workflows/**.yml'
      - '.github/workflows/**.yaml'
    branches-ignore:
      - 'main'
      - 'staging'
      - 'develop'
  pull_request:
  workflow_dispatch:

jobs:
  auto-action-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Download Action Lint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
