name: Playbook

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: How to Fix?
        uses: actions/github-script@v7
        env:
          INPUT_MESSAGE: ${{ inputs.message }}
        with:
          script: |
            const message = process.env.INPUT_MESSAGE;
            core.summary.addRaw(message, true);
            core.summary.write();
            core.setFailed(message);
